simple

diff --git a/.github/workflows/docker_test.yml b/.github/workflows/docker_test.yml
--- a/.github/workflows/docker_test.yml
+++ b/.github/workflows/docker_test.yml
@@ -8,66 +8,65 @@ jobs:
     steps:
       - run: steampipe -v
       - run: steampipe query "select 1"
-      - run: uname -a
 
-  acceptance_test:
-    name: Acceptance tests
-    needs: first-job
-    runs-on: ubuntu-latest
-    container: turbot/steampipe:latest
-    steps:
-      - name: uname
-        run: uname -a
+  # acceptance_test:
+  #   name: Acceptance tests
+  #   needs: first-job
+  #   runs-on: ubuntu-latest
+  #   container: turbot/steampipe:latest
+  #   steps:
+  #     - name: uname
+  #       run: uname -a
 
-      - name: Checkout
-        uses: actions/checkout@v3
-        with:
-          submodules: true
+  #     - name: Checkout
+  #       uses: actions/checkout@v3
+  #       with:
+  #         submodules: true
 
-      - name: Set PATH
-        run: |
-          echo "PATH=$PATH:$HOME/build:$GTIHUB_WORKSPACE/tests/acceptance/lib/bats/libexec" >> $GITHUB_ENV
+  #     - name: Set PATH
+  #       run: |
+  #         echo "PATH=$PATH:$HOME/build:$GTIHUB_WORKSPACE/tests/acceptance/lib/bats/libexec" >> $GITHUB_ENV
 
-      - name: Install DB
-        continue-on-error: false
-        run: |
-          steampipe service start
-          steampipe service stop
+  #     - name: Install DB
+  #       continue-on-error: false
+  #       run: |
+  #         steampipe service start
+  #         steampipe service stop
 
-      - name: Run Test Suite
-        id: run-test-suite
-        timeout-minutes: 15
-        continue-on-error: true
-        run: |
-          chmod +x $GITHUB_WORKSPACE/tests/acceptance/run.sh
-          $GITHUB_WORKSPACE/tests/acceptance/run.sh
-          steampipe service stop --force
+  #     - name: Run Test Suite
+  #       id: run-test-suite
+  #       timeout-minutes: 15
+  #       continue-on-error: true
+  #       run: |
+  #         chmod +x $GITHUB_WORKSPACE/tests/acceptance/run.sh
+  #         $GITHUB_WORKSPACE/tests/acceptance/run.sh
+  #         steampipe service stop --force
       
-      - name: Save Test Suite Logs
-        uses: actions/upload-artifact@v3
-        with:
-          name: test-logs
-          path: ~/.steampipe/logs
-          if-no-files-found: error
+  #     - name: Save Test Suite Logs
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: test-logs
+  #         path: ~/.steampipe/logs
+  #         if-no-files-found: error
       
-      # This job checks whether the test suite has passed or not.
-      # Since the exit_code is set only when the bats test suite pass, so we have added the if-conditional block 
-      - name: Check Test Passed/Failed
-        continue-on-error: false
-        run: |
-          if [ ${{ steps.run-test-suite.outputs.exit_code }} -eq 0 ]; then
-            exit 0
-          else
-            exit 1
-          fi
+  #     # This job checks whether the test suite has passed or not.
+  #     # Since the exit_code is set only when the bats test suite pass, so we have added the if-conditional block 
+  #     - name: Check Test Passed/Failed
+  #       continue-on-error: false
+  #       run: |
+  #         if [ ${{ steps.run-test-suite.outputs.exit_code }} -eq 0 ]; then
+  #           exit 0
+  #         else
+  #           exit 1
+  #         fi
 
-  clean_up:
-    name: Clean Up
-    needs: acceptance_test
-    runs-on: ubuntu-latest
-    steps:
-      - name: Clean up Test Suite Logs
-        uses: geekyeggo/delete-artifact@v1
-        with:
-          name: test-logs
-          failOnError: true
+  # clean_up:
+  #   name: Clean Up
+  #   needs: acceptance_test
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Clean up Test Suite Logs
+  #       uses: geekyeggo/delete-artifact@v1
+  #       with:
+  #         name: test-logs
+  #         failOnError: true
