revert Steampipe release  workflow

diff --git a/.github/workflows/docker_test.yml b/.github/workflows/docker_test.yml
--- a/.github/workflows/docker_test.yml
+++ b/.github/workflows/docker_test.yml
@@ -1,78 +1,297 @@
-name: ">>>> Docker testing"
-on: push
+name: ">>>>Steampipe Release"
+on:
+  workflow_dispatch:
+    inputs:
+      branch:
+        description: "The branch that will be built"
+        required: true
+      version:
+        description: "The version to release (must be prefixed with 'v')"
+        required: true
+
+env:
+  PROJECT_ID: steampipe
+  STEAMPIPE_UPDATE_CHECK: false
+  VERSION: ${{ github.event.inputs.version }}
+
 jobs:
-  first-job:
-    name: Check steampipe version
+  goreleaser:
+    name: Build
     runs-on: ubuntu-latest
-    container: turbot/steampipe:latest
+
     steps:
-      # - name: Checkout
-      #   uses: actions/checkout@v3
+      - name: Checkout
+        uses: actions/checkout@v3
+        with:
+          ref: ${{ github.event.inputs.branch }}
 
-      - name: Check version
-        run: steampipe -v
+      - name: Unshallow
+        run: git fetch
 
-      - name: Query
-        run: steampipe query "select 1"
+      - name: Set up Go
+        uses: actions/setup-go@v3
+        with:
+          go-version: 1.18
 
-  acceptance_test:
-    name: Acceptance tests
-    needs: first-job
-    runs-on: ubuntu-latest
-    container: turbot/steampipe:latest
-    steps:
-      - name: uname
-        run: uname -a
+      - name: Hook private repo
+        run: git config --global url."https://${{ secrets.GH_ACCESS_TOKEN }}:x-oauth-basic@github.com".insteadOf "https://github.com"
 
-      # - name: Checkout
-      #   uses: actions/checkout@v3
-      #   with:
-      #     submodules: true
+      - name: Run GoReleaser
+        uses: goreleaser/goreleaser-action@v3
+        with:
+          version: latest
+          args: release --snapshot --rm-dist --skip-publish
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Move build artifacts
+        run: |
+          mkdir ~/artifacts
+          mv $GITHUB_WORKSPACE/dist/steampipe_linux_amd64.tar.gz ~/artifacts/linux.tar.gz
+          mv $GITHUB_WORKSPACE/dist/steampipe_darwin_amd64.zip ~/artifacts/darwin.zip
+
+      - name: List Build Artifacts
+        run: ls -l ~/artifacts
+
+      - name: Save Linux Build Artifact
+        uses: actions/upload-artifact@v3
+        with:
+          name: build-artifact-linux
+          path: ~/artifacts/linux.tar.gz
+          if-no-files-found: error
+
+      - name: Save MacOS Build Artifact
+        uses: actions/upload-artifact@v3
+        with:
+          name: build-artifact-darwin
+          path: ~/artifacts/darwin.zip
+          if-no-files-found: error
+
+  # acceptance_test:
+  #   name: Acceptance tests
+  #   needs: goreleaser
+  #   strategy:
+  #     matrix:
+  #       platform: [ubuntu-latest]
+  #   runs-on: ${{ matrix.platform }}
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v3
+  #       with:
+  #         submodules: true
+  #         ref: ${{ github.event.inputs.branch }}
+
+  #     - name: Setup BATS
+  #       uses: mig4/setup-bats@v1
+  #       with:
+  #         bats-version: 1.2.1
+
+  #     - name: Prepare for downloads
+  #       id: prepare-for-downloads
+  #       run: |
+  #         mkdir ~/artifacts
+
+  #     - name: Download Linux Build Artifacts
+  #       uses: actions/download-artifact@v3
+  #       if: ${{ matrix.platform == 'ubuntu-latest' }}
+  #       with:
+  #         name: build-artifact-linux
+  #         path: ~/artifacts
+
+  #     - name: Download Darwin Build Artifacts
+  #       uses: actions/download-artifact@v3
+  #       if: ${{ matrix.platform == 'macos-latest' }}
+  #       with:
+  #         name: build-artifact-darwin
+  #         path: ~/artifacts
+
+  #     - name: Extract Darwin Artifacts and Install Binary
+  #       if: ${{ matrix.platform == 'macos-latest' }}
+  #       run: |
+  #         mkdir ~/build
+  #         unzip ~/artifacts/darwin.zip -d ~/build
+
+  #     - name: Extract Ubuntu Artifacts and Install Binary
+  #       if: ${{ matrix.platform == 'ubuntu-latest' }}
+  #       run: |
+  #         mkdir ~/build
+  #         tar -xf ~/artifacts/linux.tar.gz -C ~/build
 
   #     - name: Set PATH
   #       run: |
-  #         echo "PATH=$PATH:$HOME/build:$GTIHUB_WORKSPACE/tests/acceptance/lib/bats/libexec" >> $GITHUB_ENV
+  #         echo "PATH=$PATH:$HOME/build:$GTIHUB_WORKSPACE/tests/acceptance/lib/bats/bin" >> $GITHUB_ENV
 
-      - name: Install DB
-        continue-on-error: false
-        run: |
-          steampipe service start
-          steampipe service stop
+  #     - name: Install DB
+  #       run: |
+  #         steampipe service start
+  #         steampipe plugin install chaos
+  #         steampipe service stop --force
 
   #     - name: Run Test Suite
-  #       id: run-test-suite
-  #       timeout-minutes: 15
-  #       continue-on-error: true
+  #       timeout-minutes: 5
   #       run: |
   #         chmod +x $GITHUB_WORKSPACE/tests/acceptance/run.sh
   #         $GITHUB_WORKSPACE/tests/acceptance/run.sh
   #         steampipe service stop --force
-      
-  #     - name: Save Test Suite Logs
-  #       uses: actions/upload-artifact@v3
-  #       with:
-  #         name: test-logs
-  #         path: ~/.steampipe/logs
-  #         if-no-files-found: error
-      
-  #     # This job checks whether the test suite has passed or not.
-  #     # Since the exit_code is set only when the bats test suite pass, so we have added the if-conditional block 
-  #     - name: Check Test Passed/Failed
-  #       continue-on-error: false
-  #       run: |
-  #         if [ ${{ steps.run-test-suite.outputs.exit_code }} -eq 0 ]; then
-  #           exit 0
-  #         else
-  #           exit 1
-  #         fi
 
-  # clean_up:
-  #   name: Clean Up
-  #   needs: acceptance_test
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - name: Clean up Test Suite Logs
-  #       uses: geekyeggo/delete-artifact@v1
-  #       with:
-  #         name: test-logs
-  #         failOnError: true
+  docker_acceptance_test:
+    name: Acceptance tests(Docker)
+    needs: goreleaser
+    strategy:
+      matrix:
+        containers: [ubuntu:latest]
+    container: ${{ matrix.platform }}
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+        with:
+          submodules: true
+          ref: ${{ github.event.inputs.branch }}
+
+      - name: Setup BATS
+        uses: mig4/setup-bats@v1
+        with:
+          bats-version: 1.2.1
+
+      - name: Prepare for downloads
+        id: prepare-for-downloads
+        run: |
+          mkdir ~/artifacts
+
+      - name: Download Linux Build Artifacts
+        uses: actions/download-artifact@v3
+        if: ${{ matrix.platform == 'ubuntu-latest' }}
+        with:
+          name: build-artifact-linux
+          path: ~/artifacts
+
+      - name: Download Darwin Build Artifacts
+        uses: actions/download-artifact@v3
+        if: ${{ matrix.platform == 'macos-latest' }}
+        with:
+          name: build-artifact-darwin
+          path: ~/artifacts
+
+      - name: Extract Darwin Artifacts and Install Binary
+        if: ${{ matrix.platform == 'macos-latest' }}
+        run: |
+          mkdir ~/build
+          unzip ~/artifacts/darwin.zip -d ~/build
+
+      - name: Extract Ubuntu Artifacts and Install Binary
+        if: ${{ matrix.platform == 'ubuntu-latest' }}
+        run: |
+          mkdir ~/build
+          tar -xf ~/artifacts/linux.tar.gz -C ~/build
+
+      - name: Set PATH
+        run: |
+          echo "PATH=$PATH:$HOME/build:$GTIHUB_WORKSPACE/tests/acceptance/lib/bats/bin" >> $GITHUB_ENV
+
+      - name: Install DB
+        run: |
+          steampipe service start
+          steampipe plugin install chaos
+          steampipe service stop --force
+
+      - name: Run Test Suite
+        timeout-minutes: 5
+        run: |
+          chmod +x $GITHUB_WORKSPACE/tests/acceptance/run.sh
+          $GITHUB_WORKSPACE/tests/acceptance/run.sh
+          steampipe service stop --force
+
+  create_release_tag:
+    name: Tag Release
+    needs: [goreleaser, docker_acceptance_test]
+    runs-on: ubuntu-latest
+    steps:
+
+      - name: Trim asset version prefix and Validate
+        run: |-
+          echo $VERSION
+          trim=${VERSION#"v"}
+          echo $trim
+          if [[ $trim =~  ^[0-9]+\.[0-9]+\.[0-9]+(-.+)?$ ]]; then
+            echo "Version OK: $trim"
+          else
+            echo "Invalid version: $trim"
+            exit 1
+          fi
+          echo "VERSION=${trim}" >> $GITHUB_ENV
+          
+      - name: Checkout
+        uses: actions/checkout@v3
+        with:
+          ref: ${{ github.event.inputs.branch }}
+
+      - name: Unshallow
+        run: git fetch --prune --unshallow
+
+      - name: Tag Release
+        run: |
+          git config user.name "Steampipe GitHub Actions Bot"
+          git config user.email noreply@github.com
+          git tag ${{ github.event.inputs.version }}
+          git push origin ${{ github.event.inputs.version }}
+
+  create_release:
+    name: Release
+    needs: [create_release_tag]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+        with:
+          ref: ${{ github.event.inputs.version }}
+
+      - name: Set up Go
+        uses: actions/setup-go@v3
+        with:
+          go-version: 1.18
+
+      - name: Run GoReleaser
+        uses: goreleaser/goreleaser-action@v3
+        with:
+          version: latest
+          args: release --rm-dist
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      # - name: Setup GCloud CLI
+      #   uses: google-github-actions/setup-gcloud@v0.6.0
+      #   with:
+      #     service_account_key: ${{ secrets.GCP_GITHUB_ACTION_PUSH_ARTIFACTS }}
+      #     project_id: ${{ env.PROJECT_ID }}
+      #     export_default_credentials: true
+
+      # - name: Install GCloud Beta Components
+      #   run: |- 
+      #     gcloud config list
+      #     gcloud components install beta
+
+      # - name: Upload rpm and deb packages to artifact registry
+      #   run: |
+      #     gcloud beta artifacts yum upload steampipe-yum-repo --location=us --source=$GITHUB_WORKSPACE/dist/steampipe_linux_amd64.rpm --project steampipe
+      #     gcloud beta artifacts apt upload steampipe-apt-repo --location=us --source=$GITHUB_WORKSPACE/dist/steampipe_linux_amd64.deb --project steampipe
+
+  clean_up:
+    # let's clean up the artifacts.
+    # incase this step isn't reached,
+    # artifacts automatically expire after 90 days anyway
+    # refer:
+    #   https://docs.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts#downloading-and-deleting-artifacts-after-a-workflow-run-is-complete
+    name: Clean Up Artifacts
+    needs: create_release
+    runs-on: ubuntu-latest
+    steps:
+      - name: Clean up Linux Build
+        uses: geekyeggo/delete-artifact@v1
+        with:
+          name: build-artifact-linux
+
+      - name: Clean up Darwin Build
+        uses: geekyeggo/delete-artifact@v1
+        with:
+          name: build-artifact-darwin
