Disable homebrew updates on publish temporarily

diff --git a/.github/workflows/publish_docker.yml b/.github/workflows/publish_docker.yml
--- a/.github/workflows/publish_docker.yml
+++ b/.github/workflows/publish_docker.yml
@@ -60,53 +60,54 @@ jobs:
       - name: Image digest
         run: echo ${{ steps.docker_build.outputs.digest }}
 
-  update_homebrew_tap:  
-    name: Update homebrew-tap formula
-#    needs: publish_docker
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-        with:
-          repository: turbot/homebrew-tap
-          token: ${{ secrets.GH_ACCESS_TOKEN }}
-          ref: main
-
-      - name: Get pull request title
-        id: pr_title
-        run: >-
-          echo "PR_TITLE=$(
-            gh pr view $STEAMPIPE_VERSION --json title | jq .title | tr -d '"'
-          )" >> $GITHUB_OUTPUT
-
-      - name: Output
-        run: |
-          echo ${{ steps.pr_title.outputs.PR_TITLE }}
-          echo ${{ env.STEAMPIPE_VERSION }}
-
-      - name: Fail if PR title does not match with version
-        run: |
-          if ${{ (steps.pr_title.outputs.PR_TITLE == env.STEAMPIPE_VERSION) }} == 'true';then
-            echo "Correct version"
-          else
-            echo "Incorrect version"
-            exit 1
-          fi
-        
-      - name: Merge pull request to update brew formula
-        run: |
-          git fetch --all
-          gh pr merge $STEAMPIPE_VERSION --squash --delete-branch
-          git push origin --delete bump-brew
-
-  update_homebrew_core_formula:
-    name: Update Homebrew Core Formula
-    runs-on: macos-latest
-    steps:
-      - name: Update Homebrew core formula
-        uses: dawidd6/action-homebrew-bump-formula@v3
-        with:
-          token: ${{ secrets.GH_ACCESS_TOKEN }} # should be turbot org token?
-          formula: steampipe
-          tag: ${{ env.STEAMPIPE_VERSION }}
-          force: true
+#   update_homebrew_tap:  
+#     name: Update homebrew-tap formula
+# #    needs: publish_docker
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Checkout
+#         uses: actions/checkout@v3
+#         with:
+#           repository: turbot/homebrew-tap
+#           token: ${{ secrets.GH_ACCESS_TOKEN }}
+#           ref: main
+# 
+#       - name: Get pull request title
+#         id: pr_title
+#         run: >-
+#           echo "PR_TITLE=$(
+#             gh pr view $STEAMPIPE_VERSION --json title | jq .title | tr -d '"'
+#           )" >> $GITHUB_OUTPUT
+# 
+#       - name: Output
+#         run: |
+#           echo ${{ steps.pr_title.outputs.PR_TITLE }}
+#           echo ${{ env.STEAMPIPE_VERSION }}
+# 
+#       - name: Fail if PR title does not match with version
+#         run: |
+#           if ${{ (steps.pr_title.outputs.PR_TITLE == env.STEAMPIPE_VERSION) }} == 'true';then
+#             echo "Correct version"
+#           else
+#             echo "Incorrect version"
+#             exit 1
+#           fi
+#         
+#       - name: Merge pull request to update brew formula
+#         run: |
+#           git fetch --all
+#           gh pr merge $STEAMPIPE_VERSION --squash --delete-branch
+#           git push origin --delete bump-brew
+# 
+#   update_homebrew_core_formula:
+#     name: Update Homebrew Core Formula
+#     runs-on: macos-latest
+#     steps:
+#       - name: Update Homebrew core formula
+#         uses: dawidd6/action-homebrew-bump-formula@v3
+#         with:
+#           token: ${{ secrets.GH_ACCESS_TOKEN }} # should be turbot org token?
+#           formula: steampipe
+#           tag: ${{ env.STEAMPIPE_VERSION }}
+#           force: true
+# 
