add linux_arm_acceptance_tests

diff --git a/.github/workflows/release_cli_and_assets.yml b/.github/workflows/release_cli_and_assets.yml
--- a/.github/workflows/release_cli_and_assets.yml
+++ b/.github/workflows/release_cli_and_assets.yml
@@ -303,200 +303,189 @@ jobs:
         path: ~/artifacts/darwin.zip
         if-no-files-found: error
 
-  run_acceptance_tests:
-    name: Acceptance tests
+  # run_acceptance_tests:
+  #   name: Acceptance tests
+  #   needs: [create_test_build,build_and_release_assets]
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       platform: [ macos-latest ]
+  #       test_block:
+  #         - "migration"
+  #         - "service_and_plugin"
+  #         - "search_path"
+  #         - "chaos_and_query"
+  #         - "dynamic_schema"
+  #         - "dynamic_aggregators"
+  #         - "cache"
+  #         - "mod_install"
+  #         - "mod"
+  #         - "mod_require"
+  #         - "check"
+  #         - "performance"
+  #         - "workspace"
+  #         - "introspection"
+  #         - "cloud"
+  #         - "snapshot"
+  #         - "dashboard"
+  #         - "dashboard_parsing_validation"
+  #         - "schema_cloning"
+  #         - "exit_codes"
+  #         - "force_stop"
+  #       exclude:
+  #         - platform: macos-latest
+  #           test_block: migration
+  #         - platform: macos-latest
+  #           test_block: force_stop
+  #   runs-on: ${{ matrix.platform }}
+  #   steps:
+  #   - name: Trim asset version prefix and Validate
+  #     run: |-
+  #       echo $VERSION
+  #       trim=${VERSION#"v"}
+  #       echo $trim
+  #       if [[ $trim =~  ^[0-9]+\.[0-9]+\.[0-9]+(-.+)?$ ]]; then
+  #         echo "Version OK: $trim"
+  #       else
+  #         echo "Invalid version: $trim"
+  #         exit 1
+  #       fi
+  #       echo "VERSION=${trim}" >> $GITHUB_ENV
+
+  #   - name: Checkout
+  #     uses: actions/checkout@v3
+  #     with:
+  #       submodules: true
+  #       ref: ${{ github.event.ref }}
+
+  #   - name: Set up Go
+  #     uses: actions/setup-go@v4
+  #     with:
+  #       go-version: 1.19
+
+  #   - name: Setup BATS
+  #     uses: mig4/setup-bats@v1
+  #     with:
+  #       bats-version: 1.2.1
+
+  #   - name: Prepare for downloads
+  #     id: prepare-for-downloads
+  #     run: |
+  #       mkdir ~/artifacts
+
+  #   - name: Download Darwin Build Artifacts
+  #     uses: actions/download-artifact@v3
+  #     if: ${{ matrix.platform == 'macos-latest' }}
+  #     with:
+  #       name: build-artifact-darwin
+  #       path: ~/artifacts
+
+  #   - name: Extract Darwin Artifacts and Install Binary
+  #     if: ${{ matrix.platform == 'macos-latest' }}
+  #     run: |
+  #       mkdir ~/build
+  #       unzip ~/artifacts/darwin.zip -d ~/build
+
+  #   - name: Set PATH
+  #     run: |
+  #       echo "PATH=$PATH:$HOME/build:$GTIHUB_WORKSPACE/tests/acceptance/lib/bats-core/libexec" >> $GITHUB_ENV
+
+  #   - name: Go install jd
+  #     run: |
+  #       go install github.com/josephburnett/jd@latest
+
+  #   - name: Install DB
+  #     id: install-db
+  #     continue-on-error: false
+  #     run: |
+  #       steampipe service start
+  #       steampipe plugin install chaos chaosdynamic
+  #       steampipe service stop
+
+  #   - name: Run Test Suite
+  #     id: run-test-suite
+  #     timeout-minutes: 15
+  #     run: |
+  #       chmod +x $GITHUB_WORKSPACE/tests/acceptance/run.sh
+  #       $GITHUB_WORKSPACE/tests/acceptance/run.sh ${{ matrix.test_block }}.bats
+  #       steampipe service stop --force
+
+  linux_arm_acceptance_tests:
+    name: Linux ARM64 acceptance tests
     needs: [create_test_build,build_and_release_assets]
-    strategy:
-      fail-fast: false
-      matrix:
-        platform: [ macos-latest ]
-        test_block:
-          - "migration"
-          - "brew"
-          - "service_and_plugin"
-          - "blank_aggregators"
-          - "search_path"
-          - "chaos_and_query"
-          - "dynamic_schema"
-          - "dynamic_aggregators"
-          - "cache"
-          - "mod_install"
-          - "mod"
-          - "mod_require"
-          - "check"
-          - "performance"
-          - "workspace"
-          - "introspection"
-          - "cloud"
-          - "snapshot"
-          - "dashboard"
-          - "dashboard_parsing_validation"
-          - "schema_cloning"
-          - "exit_codes"
-          - "force_stop"
-        exclude:
-          - platform: macos-latest
-            test_block: migration
-          - platform: macos-latest
-            test_block: force_stop
-    runs-on: ${{ matrix.platform }}
+    runs-on: ubuntu-latest
     steps:
-    - name: Trim asset version prefix and Validate
-      run: |-
-        echo $VERSION
-        trim=${VERSION#"v"}
-        echo $trim
-        if [[ $trim =~  ^[0-9]+\.[0-9]+\.[0-9]+(-.+)?$ ]]; then
-          echo "Version OK: $trim"
-        else
-          echo "Invalid version: $trim"
-          exit 1
-        fi
-        echo "VERSION=${trim}" >> $GITHUB_ENV
+      - name: Checkout
+        uses: actions/checkout@v3
+        with:
+          submodules: true
+          ref: ${{ github.event.ref }}
 
-    - name: Checkout
-      uses: actions/checkout@v3
-      with:
-        submodules: true
-        ref: ${{ github.event.ref }}
+      - name: Configure AWS Credentials
+        run: |
+          mkdir ~/.aws
+          echo -e "[default]\naws_access_key_id = ${{ secrets.ACC_TEST_ARM_LINUX_AWS_ACCESS_KEY_ID }}\naws_secret_access_key = ${{ secrets.ACC_TEST_ARM_LINUX_AWS_SECRET_ACCESS_KEY }}\nregion = ap-south-1" > ~/.aws/credentials
 
-    - name: Set up Go
-      uses: actions/setup-go@v4
-      with:
-        go-version: 1.19
+      - name: SSH into the system and run tests
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.ACC_TEST_ARM_LINUX_AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.ACC_TEST_ARM_LINUX_AWS_SECRET_ACCESS_KEY }}
+          AWS_DEFAULT_REGION: 'ap-south-1'
+          PRIVATE_KEY: ${{ secrets.ACC_TEST_ARM_LINUX_AWS_PRIVATE_KEY  }}
+        run: |
+          # echo $ref
+          ref=${{ github.event.ref }}
 
-    - name: Setup BATS
-      uses: mig4/setup-bats@v1
-      with:
-        bats-version: 1.2.1
+          # get public IP of this runner
+          ip=$(dig +short myip.opendns.com @resolver1.opendns.com)
+          echo $ip
 
-    - name: Prepare for downloads
-      id: prepare-for-downloads
-      run: |
-        mkdir ~/artifacts
+          # set PAGER to empty to not get cli output automatically being sent to vim
+          export PAGER=
 
-    - name: Download Darwin Build Artifacts
-      uses: actions/download-artifact@v3
-      if: ${{ matrix.platform == 'macos-latest' }}
-      with:
-        name: build-artifact-darwin
-        path: ~/artifacts
+          # whitelist the ip, add the ip to the security group to allow access into the instance
+          aws ec2 authorize-security-group-ingress --group-name pskr-sg --protocol tcp --port 22 --cidr $ip/32 --region ap-south-1
 
-    - name: Extract Darwin Artifacts and Install Binary
-      if: ${{ matrix.platform == 'macos-latest' }}
-      run: |
-        mkdir ~/build
-        unzip ~/artifacts/darwin.zip -d ~/build
+          #start instance
+          aws ec2 start-instances --instance-ids i-09b87c86dfdfcd2bd --region ap-south-1 --output text
+          echo "starting instance..."
+          sleep 60
 
-    - name: Set PATH
-      run: |
-        echo "PATH=$PATH:$HOME/build:$GTIHUB_WORKSPACE/tests/acceptance/lib/bats-core/libexec" >> $GITHUB_ENV
+          # get the public ip and status of the instance
+          public_ip=$(aws ec2 describe-instances --instance-ids i-09b87c86dfdfcd2bd --query 'Reservations[*].Instances[*].PublicDnsName' --region ap-south-1 --output text)
+          status=$(aws ec2 describe-instance-status --instance-ids i-09b87c86dfdfcd2bd --query 'InstanceStatuses[*].InstanceState.Name' --region ap-south-1 --output text)
+          echo $public_ip
+          echo $status
 
-    - name: Go install jd
-      run: |
-        go install github.com/josephburnett/jd@latest
+          # check if the instance is available for use, if not, then wait for it
+          while [ $status != "running" ] ; do
+            echo "instance not yet available"
+            sleep 5
+            status=$(aws ec2 describe-instance-status --instance-ids i-09b87c86dfdfcd2bd --query 'InstanceStatuses[*].InstanceState.Name' --region ap-south-1 --output text)
+          done
 
-    - name: Install DB
-      id: install-db
-      continue-on-error: false
-      run: |
-        steampipe service start
-        steampipe plugin install chaos chaosdynamic
-        steampipe service stop
+          # set up the private key
+          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
 
-    - name: Run Test Suite
-      id: run-test-suite
-      timeout-minutes: 15
-      run: |
-        chmod +x $GITHUB_WORKSPACE/tests/acceptance/run.sh
-        $GITHUB_WORKSPACE/tests/acceptance/run.sh ${{ matrix.test_block }}.bats
-        steampipe service stop --force
-#
-#  docker_acceptance_test_debian:
-#   name: Acceptance tests(Docker - Debian)
-#   needs: [create_test_build,build_and_release_assets]
-#   runs-on: ubuntu-latest
-#   steps:
-#    - name: Checkout
-#      uses: actions/checkout@v3
-#      with:
-#        ref: ${{ github.event.ref }}
-#
-#    - name: Prepare for downloads
-#      id: prepare-for-downloads
-#      run: |
-#        mkdir ~/artifacts
-#
-#    - name: Download Linux Build Artifacts
-#      uses: actions/download-artifact@v3
-#      with:
-#        name: build-artifact-linux
-#        path: ~/artifacts
-#
-#    - name: Extract Ubuntu Artifacts and Install Binary
-#      run: |
-#        mkdir ~/build
-#        tar -xf ~/artifacts/linux.tar.gz -C ~/build
-#
-#    - name: Copy binary
-#      run: |
-#        cp ~/build/steampipe tests/dockertesting/debian
-#
-#    - name: Build steampipe docker images
-#      run: |
-#        docker build -t spdebian tests/dockertesting/debian --build-arg TARGETBRANCH="${{ github.event.ref }}"
-#        docker images
-#
-#    - name: Create a container and run the test suite
-#      timeout-minutes: 15
-#      run: |
-#        docker run --name steampipe-deb `docker images -q spdebian`
-#        echo "docker run complete"
-#
-#  docker_acceptance_test_oraclelinux:
-#   name: Acceptance tests(Docker - OracleLinux)
-#   needs: [create_test_build,build_and_release_assets]
-#   runs-on: ubuntu-latest
-#   steps:
-#    - name: Checkout
-#      uses: actions/checkout@v3
-#      with:
-#        ref: ${{ github.event.ref }}
-#
-#    - name: Prepare for downloads
-#      id: prepare-for-downloads
-#      run: |
-#        mkdir ~/artifacts
-#
-#    - name: Download Linux Build Artifacts
-#      uses: actions/download-artifact@v3
-#      with:
-#        name: build-artifact-linux
-#        path: ~/artifacts
-#
-#    - name: Extract Ubuntu Artifacts and Install Binary
-#      run: |
-#        mkdir ~/build
-#        tar -xf ~/artifacts/linux.tar.gz -C ~/build
-#
-#    - name: Copy binary
-#      run: |
-#        cp ~/build/steampipe tests/dockertesting/oraclelinux
-#
-#    - name: Build steampipe docker images
-#      run: |
-#        docker build -t sporacle tests/dockertesting/oraclelinux --build-arg TARGETBRANCH="${{ github.event.ref }}"
-#        docker images
-#
-#    - name: Create a container and run the test suite
-#      timeout-minutes: 15
-#      run: |
-#        docker run --name steampipe-oracle `docker images -q sporacle`
-#        echo "docker run complete"
+          #pwd
+          pwd
+          chmod +x tests/acceptance/run-linux-arm.sh
+
+          # ssh into the instance and run the full acceptance test suite
+          # ssh -o StrictHostKeyChecking=accept-new -i private_key ubuntu@$public_ip 'bash -s' < tests/acceptance/run-linux-arm.sh $ref
+
+          # stop instance
+          aws ec2 stop-instances --instance-ids i-09b87c86dfdfcd2bd --region ap-south-1
+
+          # remove the ip from the security group
+          aws ec2 revoke-security-group-ingress --group-name pskr-sg --protocol tcp --port 22 --cidr $ip/32 --region ap-south-1
+
+          # fin
+          echo "fin"
 
   create_release_tag:
     name: Tag Release
-    needs: [run_acceptance_tests]
+    needs: [linux_arm_acceptance_tests]
     runs-on: ubuntu-latest
     steps:
     - name: Trim asset version prefix and Validate
