updates to workflows

diff --git a/.github/workflows/release_cli.yml b/.github/workflows/release_cli.yml
--- a/.github/workflows/release_cli.yml
+++ b/.github/workflows/release_cli.yml
@@ -133,11 +133,25 @@ jobs:
           $GITHUB_WORKSPACE/tests/acceptance/run.sh
           steampipe service stop --force
 
-  create_release:
-    name: Release
+  create_release_tag:
+    name: Tag Release
     needs: [goreleaser, acceptance_test]
     runs-on: ubuntu-latest
     steps:
+
+      - name: Trim asset version prefix and Validate
+        run: |-
+          echo $VERSION
+          trim=${VERSION#"v"}
+          echo $trim
+          if [[ $trim =~  ^[0-9]+\.[0-9]+\.[0-9]+(-.+)?$ ]]; then
+            echo "Version OK: $trim"
+          else
+            echo "Invalid version: $trim"
+            exit 1
+          fi
+          echo "VERSION=${trim}" >> $GITHUB_ENV
+          
       - name: Checkout
         uses: actions/checkout@v2
         with:
@@ -146,13 +160,27 @@ jobs:
       - name: Unshallow
         run: git fetch --prune --unshallow
 
+      - name: Tag Release
+        run: |
+          git config user.name "Steampipe GitHub Actions Bot"
+          git config user.email noreply@github.com
+          git tag ${{ github.event.inputs.version }}
+          git push origin ${{ github.event.inputs.version }}
+
+  create_release:
+    name: Release
+    needs: [create_release_tag]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+        with:
+          ref: ${{ github.event.inputs.branch }}
+
       - name: Set up Go
         uses: actions/setup-go@v2
         with:
           go-version: 1.17
-
-      - name: Hook private repo
-        run: git config --global url."https://${{ secrets.GH_ACCESS_TOKEN }}:x-oauth-basic@github.com".insteadOf "https://github.com"
 
       - name: Tag Release
         run: |
diff --git a/.github/workflows/release_cli_and_assets.yml b/.github/workflows/release_cli_and_assets.yml
--- a/.github/workflows/release_cli_and_assets.yml
+++ b/.github/workflows/release_cli_and_assets.yml
@@ -51,24 +51,37 @@ jobs:
       status: ${{ steps.verify.conclusion }}
 
     steps:
-    - name: Get GCloud CLI
-      uses: google-github-actions/setup-gcloud@v0.4.0
-      with:
-        service_account_key: ${{ secrets.GCP_GITHUB_ACTION_PUSH_ARTIFACTS }}
-        project_id: ${{ env.PROJECT_ID }}
-        export_default_credentials: true
+      - name: Trim asset version prefix and Validate
+          run: |-
+            echo $VERSION
+            trim=${VERSION#"v"}
+            echo $trim
+            if [[ $trim =~  ^[0-9]+\.[0-9]+\.[0-9]+(-.+)?$ ]]; then
+              echo "Version OK: $trim"
+            else
+              echo "Invalid version: $trim"
+              exit 1
+            fi
+            echo "VERSION=${trim}" >> $GITHUB_ENV
 
-    - name: Setup GCloud CLI
-      run: |- 
-        echo ${{ secrets.STEAMPIPE_REGISTRY_SA_KEY }}
-        gcloud config list
-        gcloud components install beta
-        gcloud components install alpha --quiet
+      - name: Get GCloud CLI
+        uses: google-github-actions/setup-gcloud@v0.4.0
+        with:
+          service_account_key: ${{ secrets.GCP_GITHUB_ACTION_PUSH_ARTIFACTS }}
+          project_id: ${{ env.PROJECT_ID }}
+          export_default_credentials: true
 
-    - name: Verify
-      id: verify
-      continue-on-error: true
-      run: |-
+      - name: Setup GCloud CLI
+        run: |- 
+          echo ${{ secrets.STEAMPIPE_REGISTRY_SA_KEY }}
+          gcloud config list
+          gcloud components install beta
+          gcloud components install alpha --quiet
+
+      - name: Verify
+        id: verify
+        continue-on-error: true
+        run: |-
         [ $(gcloud beta artifacts docker tags list ${{ env.CORE_REPO }}/${{ env.ASSET_IMAGE_NAME }}  --project ${{ env.PROJECT_ID }}  --format=json | jq 'map(select(.tag | endswith("${{ env.VERSION }}"))) | length') -eq 0 ]
 
   build_and_release_assets:
@@ -77,134 +90,159 @@ jobs:
     if: needs.verify_asset_unreleased.outputs.status == 'success'
     runs-on: ubuntu-latest
     steps:
+      - name: Trim asset version prefix and Validate
+        run: |-
+          echo $VERSION
+          trim=${VERSION#"v"}
+          echo $trim
+          if [[ $trim =~  ^[0-9]+\.[0-9]+\.[0-9]+(-.+)?$ ]]; then
+            echo "Version OK: $trim"
+          else
+            echo "Invalid version: $trim"
+            exit 1
+          fi
+          echo "VERSION=${trim}" >> $GITHUB_ENV
 
-    - name: Get GCloud CLI
-      uses: google-github-actions/setup-gcloud@v0.4.0
-      with:
-        service_account_key: ${{ secrets.GCP_GITHUB_ACTION_PUSH_ARTIFACTS }}
-        project_id: ${{ env.PROJECT_ID }}
-        export_default_credentials: true
+      - name: Get GCloud CLI
+        uses: google-github-actions/setup-gcloud@v0.4.0
+        with:
+          service_account_key: ${{ secrets.GCP_GITHUB_ACTION_PUSH_ARTIFACTS }}
+          project_id: ${{ env.PROJECT_ID }}
+          export_default_credentials: true
 
-    - name: Setup GCloud CLI
-      run: |- 
-        echo ${{ secrets.STEAMPIPE_REGISTRY_SA_KEY }}
-        gcloud config list
-        gcloud components install beta
-        gcloud components install alpha --quiet
+      - name: Setup GCloud CLI
+        run: |- 
+          echo ${{ secrets.STEAMPIPE_REGISTRY_SA_KEY }}
+          gcloud config list
+          gcloud components install beta
+          gcloud components install alpha --quiet
 
-    - name: Verify ORAS
-      run: |- 
-        gcloud beta auth configure-docker us-docker.pkg.dev
-        oras version
-      
-    - name: Checkout
-      uses: actions/checkout@v2
-      with:
-        ref: ${{ github.event.inputs.branch }}
+      - name: Verify ORAS
+        run: |- 
+          gcloud beta auth configure-docker us-docker.pkg.dev
+          oras version
+        
+      - name: Checkout
+        uses: actions/checkout@v2
+        with:
+          ref: ${{ github.event.inputs.branch }}
 
-    - name: Setup Node
-      uses: actions/setup-node@v2
-      with:
-        node-version: '16'
+      - name: Setup Node
+        uses: actions/setup-node@v2
+        with:
+          node-version: '16'
 
-    - name: Setup Yarn
-      run: |-
-        rm -rf ./build
-      working-directory: ./ui/report
+      - name: Setup Yarn
+        run: |-
+          rm -rf ./build
+        working-directory: ./ui/report
 
-    - name: YARN Install
-      run: |-
-        unset CI
-        yarn install
-      working-directory: ./ui/report
+      - name: YARN Install
+        run: |-
+          unset CI
+          yarn install
+        working-directory: ./ui/report
 
-    - name: Run Unit Tests
-      run: |
-        yarn install
-        CI=true yarn test
-      working-directory: ./ui/report
+      - name: Run Unit Tests
+        run: |
+          yarn install
+          CI=true yarn test
+        working-directory: ./ui/report
 
-    - name: YARN Build
-      run: |-
-        unset CI
-        yarn build
-      working-directory: ./ui/report
+      - name: YARN Build
+        run: |-
+          unset CI
+          yarn build
+        working-directory: ./ui/report
 
-    - name: Move Build Assets
-      run: |-
-        mkdir -p report_ui_build
-        mv ./ui/report/build/* report_ui_build/
-        ls -la report_ui_build
+      - name: Move Build Assets
+        run: |-
+          mkdir -p report_ui_build
+          mv ./ui/report/build/* report_ui_build/
+          ls -la report_ui_build
 
-    - name: Create a version file
-      run: |-
-        JSON_STRING=$( jq -n \
+      - name: Create a version file
+        run: |-
+          JSON_STRING=$( jq -n \
+              --arg version "$VERSION" \
+            '{
+                "version":$version,
+            }' )
+
+            echo $JSON_STRING > ./report_ui_build/versions.json
+
+      - name: Create Image Config File
+        run: |-
+          JSON_STRING=$( jq -n \
+            --arg name "${{ env.ASSET_IMAGE_NAME }}" \
+            --arg organization "$ORG" \
             --arg version "$VERSION" \
-          '{
-              "version":$version,
-          }' )
+            --arg schemaVersion "$CONFIG_SCHEMA_VERSION" \
+            '{schemaVersion: $schemaVersion, assets: { name: $name, organization: $organization, version: $version} }' )
 
-          echo $JSON_STRING > ./report_ui_build/versions.json
+          echo $JSON_STRING > config.json
 
-    - name: Create Image Config File
-      run: |-
-        JSON_STRING=$( jq -n \
-          --arg name "${{ env.ASSET_IMAGE_NAME }}" \
-          --arg organization "$ORG" \
-          --arg version "$VERSION" \
-          --arg schemaVersion "$CONFIG_SCHEMA_VERSION" \
-          '{schemaVersion: $schemaVersion, assets: { name: $name, organization: $organization, version: $version} }' )
+      - name: Create Image Annotations File
+        run: |-
+          JSON_STRING=$( jq -n \
+              --arg title "${{ env.ASSET_IMAGE_NAME }}" \
+              --arg desc "$ORG" \
+              --arg version "$VERSION" \
+              --arg timestamp "$(date +%FT%T%z)" \
+              --arg vendor "Turbot HQ, Inc." \
+            '{
+                "$manifest": {
+                    "org.opencontainers.image.title": $title,
+                    "org.opencontainers.image.description": $desc,
+                    "org.opencontainers.image.version": $version,
+                    "org.opencontainers.image.created": $timestamp,
+                    "org.opencontainers.image.vendor":  $vendor
+                }
+            }' )
 
-        echo $JSON_STRING > config.json
+            echo $JSON_STRING > annotations.json        
 
-    - name: Create Image Annotations File
-      run: |-
-        JSON_STRING=$( jq -n \
-            --arg title "${{ env.ASSET_IMAGE_NAME }}" \
-            --arg desc "$ORG" \
-            --arg version "$VERSION" \
-            --arg timestamp "$(date +%FT%T%z)" \
-            --arg vendor "Turbot HQ, Inc." \
-          '{
-              "$manifest": {
-                  "org.opencontainers.image.title": $title,
-                  "org.opencontainers.image.description": $desc,
-                  "org.opencontainers.image.version": $version,
-                  "org.opencontainers.image.created": $timestamp,
-                  "org.opencontainers.image.vendor":  $vendor
-              }
-          }' )
+      - name: Generate Image REF
+        id: image_ref
+        run: |
+          cat config.json
+          cat annotations.json
+          cat report_ui_build/versions.json
+          REF="${{ env.CORE_REPO }}/${{ env.ASSET_IMAGE_NAME }}:$GITHUB_RUN_ID"
+          echo "::set-output name=REF::$REF"
 
-          echo $JSON_STRING > annotations.json        
+      - name: Push to registry
+        run: |-
+          oras push ${{ steps.image_ref.outputs.REF }} \
+            --manifest-config config.json:application/vnd.turbot.steampipe.config.v1+json \
+            --manifest-annotations annotations.json \
+            report_ui_build:application/vnd.turbot.steampipe.assets.report.layer.v1+tar \
 
-    - name: Generate Image REF
-      id: image_ref
-      run: |
-        cat config.json
-        cat annotations.json
-        cat report_ui_build/versions.json
-        REF="${{ env.CORE_REPO }}/${{ env.ASSET_IMAGE_NAME }}:$GITHUB_RUN_ID"
-        echo "::set-output name=REF::$REF"
-
-    - name: Push to registry
-      run: |-
-        oras push ${{ steps.image_ref.outputs.REF }} \
-          --manifest-config config.json:application/vnd.turbot.steampipe.config.v1+json \
-          --manifest-annotations annotations.json \
-          report_ui_build:application/vnd.turbot.steampipe.assets.report.layer.v1+tar \
-
-    - name: Set version tags on Pushed Image
-      uses: ./.github/actions/semver-tags
-      id: semver
-      with:
-        image-to-tag: "${{ steps.image_ref.outputs.REF }}"
-        image-version: ${{ env.VERSION }}
+      - name: Set version tags on Pushed Image
+        uses: ./.github/actions/semver-tags
+        id: semver
+        with:
+          image-to-tag: "${{ steps.image_ref.outputs.REF }}"
+          image-version: ${{ env.VERSION }}
 
   create_test_build:
     name: Create Test Build
     runs-on: ubuntu-latest
     needs: [verify_input]
     steps:
+      - name: Trim asset version prefix and Validate
+        run: |-
+          echo $VERSION
+          trim=${VERSION#"v"}
+          echo $trim
+          if [[ $trim =~  ^[0-9]+\.[0-9]+\.[0-9]+(-.+)?$ ]]; then
+            echo "Version OK: $trim"
+          else
+            echo "Invalid version: $trim"
+            exit 1
+          fi
+          echo "VERSION=${trim}" >> $GITHUB_ENV
+          
       - name: Checkout
         uses: actions/checkout@v2
         with:
@@ -257,6 +295,19 @@ jobs:
         platform: [ubuntu-latest]
     runs-on: ${{ matrix.platform }}
     steps:
+      - name: Trim asset version prefix and Validate
+        run: |-
+          echo $VERSION
+          trim=${VERSION#"v"}
+          echo $trim
+          if [[ $trim =~  ^[0-9]+\.[0-9]+\.[0-9]+(-.+)?$ ]]; then
+            echo "Version OK: $trim"
+          else
+            echo "Invalid version: $trim"
+            exit 1
+          fi
+          echo "VERSION=${trim}" >> $GITHUB_ENV
+          
       - name: Checkout
         uses: actions/checkout@v2
         with:
@@ -321,6 +372,19 @@ jobs:
     needs: [run_acceptance_tests]
     runs-on: ubuntu-latest
     steps:
+      - name: Trim asset version prefix and Validate
+        run: |-
+          echo $VERSION
+          trim=${VERSION#"v"}
+          echo $trim
+          if [[ $trim =~  ^[0-9]+\.[0-9]+\.[0-9]+(-.+)?$ ]]; then
+            echo "Version OK: $trim"
+          else
+            echo "Invalid version: $trim"
+            exit 1
+          fi
+          echo "VERSION=${trim}" >> $GITHUB_ENV
+          
       - name: Checkout
         uses: actions/checkout@v2
         with:
@@ -341,6 +405,19 @@ jobs:
     needs: [create_release_tag]
     runs-on: ubuntu-latest
     steps:
+      - name: Trim asset version prefix and Validate
+        run: |-
+          echo $VERSION
+          trim=${VERSION#"v"}
+          echo $trim
+          if [[ $trim =~  ^[0-9]+\.[0-9]+\.[0-9]+(-.+)?$ ]]; then
+            echo "Version OK: $trim"
+          else
+            echo "Invalid version: $trim"
+            exit 1
+          fi
+          echo "VERSION=${trim}" >> $GITHUB_ENV
+          
       - name: Checkout
         uses: actions/checkout@v2
         with:
