Temporarily disable acceptance tests

diff --git a/.github/workflows/release_cli_and_assets.yml b/.github/workflows/release_cli_and_assets.yml
--- a/.github/workflows/release_cli_and_assets.yml
+++ b/.github/workflows/release_cli_and_assets.yml
@@ -292,166 +292,166 @@ jobs:
         path: ~/artifacts/darwin.zip
         if-no-files-found: error
 
-  run_acceptance_tests:
-    name: Run CLI Acceptance tests
-    needs: [create_test_build,build_and_release_assets]
-    strategy:
-      matrix:
-        platform: [ macos-latest ]
-    runs-on: ${{ matrix.platform }}
-    steps:
-    - name: Trim asset version prefix and Validate
-      run: |-
-        echo $VERSION
-        trim=${VERSION#"v"}
-        echo $trim
-        if [[ $trim =~  ^[0-9]+\.[0-9]+\.[0-9]+(-.+)?$ ]]; then
-          echo "Version OK: $trim"
-        else
-          echo "Invalid version: $trim"
-          exit 1
-        fi
-        echo "VERSION=${trim}" >> $GITHUB_ENV
-
-    - name: Checkout
-      uses: actions/checkout@v3
-      with:
-        submodules: true
-        ref: ${{ github.event.inputs.branch }}
-
-    - name: Setup BATS
-      uses: mig4/setup-bats@v1
-      with:
-        bats-version: 1.2.1
-
-    - name: Prepare for downloads
-      id: prepare-for-downloads
-      run: |
-        mkdir ~/artifacts
-
-    - name: Download Linux Build Artifacts
-      uses: actions/download-artifact@v3
-      if: ${{ matrix.platform == 'ubuntu-latest' }}
-      with:
-        name: build-artifact-linux
-        path: ~/artifacts
-
-    - name: Download Darwin Build Artifacts
-      uses: actions/download-artifact@v3
-      if: ${{ matrix.platform == 'macos-latest' }}
-      with:
-        name: build-artifact-darwin
-        path: ~/artifacts
-
-    - name: Extract Darwin Artifacts and Install Binary
-      if: ${{ matrix.platform == 'macos-latest' }}
-      run: |
-        mkdir ~/build
-        unzip ~/artifacts/darwin.zip -d ~/build
-
-    - name: Extract Ubuntu Artifacts and Install Binary
-      if: ${{ matrix.platform == 'ubuntu-latest' }}
-      run: |
-        mkdir ~/build
-        tar -xf ~/artifacts/linux.tar.gz -C ~/build
-
-    - name: Set PATH
-      run: |
-        echo "PATH=$PATH:$HOME/build:$GTIHUB_WORKSPACE/tests/acceptance/lib/bats/bin" >> $GITHUB_ENV
-
-    - name: Install DB
-      run: |
-        steampipe plugin install chaos
-
-    - name: Run Test Suite
-      timeout-minutes: 30
-      run: |
-        chmod +x $GITHUB_WORKSPACE/tests/acceptance/run.sh
-        $GITHUB_WORKSPACE/tests/acceptance/run.sh
-
-  docker_acceptance_test_debian:
-    name: Acceptance tests(Docker - Debian)
-    needs: [create_test_build,build_and_release_assets]
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-        with:
-          ref: ${{ github.event.inputs.branch }}
-
-      - name: Prepare for downloads
-        id: prepare-for-downloads
-        run: |
-          mkdir ~/artifacts
-
-      - name: Download Linux Build Artifacts
-        uses: actions/download-artifact@v3
-        with:
-          name: build-artifact-linux
-          path: ~/artifacts
-
-      - name: Extract Ubuntu Artifacts and Install Binary
-        run: |
-          mkdir ~/build
-          tar -xf ~/artifacts/linux.tar.gz -C ~/build
-
-      - name: Copy binary
-        run: |
-          cp ~/build/steampipe tests/dockertesting/debian
-
-      - name: Build steampipe docker images
-        run: |
-          docker build -t spdebian tests/dockertesting/debian --build-arg TARGETBRANCH="${{ github.event.inputs.branch }}"
-          docker images
-
-      - name: Create a container and run the test suite
-        run: |
-          docker run --name steampipe-deb `docker images -q spdebian`
-          echo "docker run complete"
-  
-  docker_acceptance_test_oraclelinux:
-    name: Acceptance tests(Docker - OracleLinux)
-    needs: [create_test_build,build_and_release_assets]
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-        with:
-          ref: ${{ github.event.inputs.branch }}
-
-      - name: Prepare for downloads
-        id: prepare-for-downloads
-        run: |
-          mkdir ~/artifacts
-
-      - name: Download Linux Build Artifacts
-        uses: actions/download-artifact@v3
-        with:
-          name: build-artifact-linux
-          path: ~/artifacts
-
-      - name: Extract Ubuntu Artifacts and Install Binary
-        run: |
-          mkdir ~/build
-          tar -xf ~/artifacts/linux.tar.gz -C ~/build
-
-      - name: Copy binary
-        run: |
-          cp ~/build/steampipe tests/dockertesting/oraclelinux
-      
-      - name: Build steampipe docker images
-        run: |
-          docker build -t sporacle tests/dockertesting/oraclelinux --build-arg TARGETBRANCH="${{ github.event.inputs.branch }}"
-          docker images
-
-      - name: Create a container and run the test suite
-        run: |
-          docker run --name steampipe-oracle `docker images -q sporacle`
-          echo "docker run complete"
+#  run_acceptance_tests:
+#    name: Run CLI Acceptance tests
+#    needs: [create_test_build,build_and_release_assets]
+#    strategy:
+#      matrix:
+#        platform: [ macos-latest ]
+#    runs-on: ${{ matrix.platform }}
+#    steps:
+#    - name: Trim asset version prefix and Validate
+#      run: |-
+#        echo $VERSION
+#        trim=${VERSION#"v"}
+#        echo $trim
+#        if [[ $trim =~  ^[0-9]+\.[0-9]+\.[0-9]+(-.+)?$ ]]; then
+#          echo "Version OK: $trim"
+#        else
+#          echo "Invalid version: $trim"
+#          exit 1
+#        fi
+#        echo "VERSION=${trim}" >> $GITHUB_ENV
+#
+#    - name: Checkout
+#      uses: actions/checkout@v3
+#      with:
+#        submodules: true
+#        ref: ${{ github.event.inputs.branch }}
+#
+#    - name: Setup BATS
+#      uses: mig4/setup-bats@v1
+#      with:
+#        bats-version: 1.2.1
+#
+#    - name: Prepare for downloads
+#      id: prepare-for-downloads
+#      run: |
+#        mkdir ~/artifacts
+#
+#    - name: Download Linux Build Artifacts
+#      uses: actions/download-artifact@v3
+#      if: ${{ matrix.platform == 'ubuntu-latest' }}
+#      with:
+#        name: build-artifact-linux
+#        path: ~/artifacts
+#
+#    - name: Download Darwin Build Artifacts
+#      uses: actions/download-artifact@v3
+#      if: ${{ matrix.platform == 'macos-latest' }}
+#      with:
+#        name: build-artifact-darwin
+#        path: ~/artifacts
+#
+#    - name: Extract Darwin Artifacts and Install Binary
+#      if: ${{ matrix.platform == 'macos-latest' }}
+#      run: |
+#        mkdir ~/build
+#        unzip ~/artifacts/darwin.zip -d ~/build
+#
+#    - name: Extract Ubuntu Artifacts and Install Binary
+#      if: ${{ matrix.platform == 'ubuntu-latest' }}
+#      run: |
+#        mkdir ~/build
+#        tar -xf ~/artifacts/linux.tar.gz -C ~/build
+#
+#    - name: Set PATH
+#      run: |
+#        echo "PATH=$PATH:$HOME/build:$GTIHUB_WORKSPACE/tests/acceptance/lib/bats/bin" >> $GITHUB_ENV
+#
+#    - name: Install DB
+#      run: |
+#        steampipe plugin install chaos
+#
+#    - name: Run Test Suite
+#      timeout-minutes: 30
+#      run: |
+#        chmod +x $GITHUB_WORKSPACE/tests/acceptance/run.sh
+#        $GITHUB_WORKSPACE/tests/acceptance/run.sh
+#
+#  docker_acceptance_test_debian:
+#    name: Acceptance tests(Docker - Debian)
+#    needs: [create_test_build,build_and_release_assets]
+#    runs-on: ubuntu-latest
+#    steps:
+#      - name: Checkout
+#        uses: actions/checkout@v3
+#        with:
+#          ref: ${{ github.event.inputs.branch }}
+#
+#      - name: Prepare for downloads
+#        id: prepare-for-downloads
+#        run: |
+#          mkdir ~/artifacts
+#
+#      - name: Download Linux Build Artifacts
+#        uses: actions/download-artifact@v3
+#        with:
+#          name: build-artifact-linux
+#          path: ~/artifacts
+#
+#      - name: Extract Ubuntu Artifacts and Install Binary
+#        run: |
+#          mkdir ~/build
+#          tar -xf ~/artifacts/linux.tar.gz -C ~/build
+#
+#      - name: Copy binary
+#        run: |
+#          cp ~/build/steampipe tests/dockertesting/debian
+#
+#      - name: Build steampipe docker images
+#        run: |
+#          docker build -t spdebian tests/dockertesting/debian --build-arg TARGETBRANCH="${{ github.event.inputs.branch }}"
+#          docker images
+#
+#      - name: Create a container and run the test suite
+#        run: |
+#          docker run --name steampipe-deb `docker images -q spdebian`
+#          echo "docker run complete"
+#
+#  docker_acceptance_test_oraclelinux:
+#    name: Acceptance tests(Docker - OracleLinux)
+#    needs: [create_test_build,build_and_release_assets]
+#    runs-on: ubuntu-latest
+#    steps:
+#      - name: Checkout
+#        uses: actions/checkout@v3
+#        with:
+#          ref: ${{ github.event.inputs.branch }}
+#
+#      - name: Prepare for downloads
+#        id: prepare-for-downloads
+#        run: |
+#          mkdir ~/artifacts
+#
+#      - name: Download Linux Build Artifacts
+#        uses: actions/download-artifact@v3
+#        with:
+#          name: build-artifact-linux
+#          path: ~/artifacts
+#
+#      - name: Extract Ubuntu Artifacts and Install Binary
+#        run: |
+#          mkdir ~/build
+#          tar -xf ~/artifacts/linux.tar.gz -C ~/build
+#
+#      - name: Copy binary
+#        run: |
+#          cp ~/build/steampipe tests/dockertesting/oraclelinux
+#
+#      - name: Build steampipe docker images
+#        run: |
+#          docker build -t sporacle tests/dockertesting/oraclelinux --build-arg TARGETBRANCH="${{ github.event.inputs.branch }}"
+#          docker images
+#
+#      - name: Create a container and run the test suite
+#        run: |
+#          docker run --name steampipe-oracle `docker images -q sporacle`
+#          echo "docker run complete"
 
   create_release_tag:
     name: Tag Release
-    needs: [run_acceptance_tests, docker_acceptance_test_debian, docker_acceptance_test_oraclelinux]
+    needs: [create_test_build,build_and_release_assets]
     runs-on: ubuntu-latest
     steps:
     - name: Trim asset version prefix and Validate
