re-enable other acc tests

diff --git a/.github/workflows/release_cli_and_assets.yml b/.github/workflows/release_cli_and_assets.yml
--- a/.github/workflows/release_cli_and_assets.yml
+++ b/.github/workflows/release_cli_and_assets.yml
@@ -303,116 +303,116 @@ jobs:
         path: ~/artifacts/darwin.zip
         if-no-files-found: error
 
-  # run_acceptance_tests:
-  #   name: Acceptance tests
-  #   needs: [create_test_build,build_and_release_assets]
-  #   strategy:
-  #     fail-fast: false
-  #     matrix:
-  #       platform: [ macos-latest ]
-  #       test_block:
-  #         - "migration"
-  #         - "service_and_plugin"
-  #         - "search_path"
-  #         - "chaos_and_query"
-  #         - "dynamic_schema"
-  #         - "dynamic_aggregators"
-  #         - "cache"
-  #         - "mod_install"
-  #         - "mod"
-  #         - "mod_require"
-  #         - "check"
-  #         - "performance"
-  #         - "workspace"
-  #         - "introspection"
-  #         - "cloud"
-  #         - "snapshot"
-  #         - "dashboard"
-  #         - "dashboard_parsing_validation"
-  #         - "schema_cloning"
-  #         - "exit_codes"
-  #         - "force_stop"
-  #       exclude:
-  #         - platform: macos-latest
-  #           test_block: migration
-  #         - platform: macos-latest
-  #           test_block: force_stop
-  #   runs-on: ${{ matrix.platform }}
-  #   steps:
-  #   - name: Trim asset version prefix and Validate
-  #     run: |-
-  #       echo $VERSION
-  #       trim=${VERSION#"v"}
-  #       echo $trim
-  #       if [[ $trim =~  ^[0-9]+\.[0-9]+\.[0-9]+(-.+)?$ ]]; then
-  #         echo "Version OK: $trim"
-  #       else
-  #         echo "Invalid version: $trim"
-  #         exit 1
-  #       fi
-  #       echo "VERSION=${trim}" >> $GITHUB_ENV
+  run_acceptance_tests:
+    name: Acceptance tests
+    needs: [create_test_build,build_and_release_assets]
+    strategy:
+      fail-fast: false
+      matrix:
+        platform: [ macos-latest ]
+        test_block:
+          - "migration"
+          - "service_and_plugin"
+          - "search_path"
+          - "chaos_and_query"
+          - "dynamic_schema"
+          - "dynamic_aggregators"
+          - "cache"
+          - "mod_install"
+          - "mod"
+          - "mod_require"
+          - "check"
+          - "performance"
+          - "workspace"
+          - "introspection"
+          - "cloud"
+          - "snapshot"
+          - "dashboard"
+          - "dashboard_parsing_validation"
+          - "schema_cloning"
+          - "exit_codes"
+          - "force_stop"
+        exclude:
+          - platform: macos-latest
+            test_block: migration
+          - platform: macos-latest
+            test_block: force_stop
+    runs-on: ${{ matrix.platform }}
+    steps:
+    - name: Trim asset version prefix and Validate
+      run: |-
+        echo $VERSION
+        trim=${VERSION#"v"}
+        echo $trim
+        if [[ $trim =~  ^[0-9]+\.[0-9]+\.[0-9]+(-.+)?$ ]]; then
+          echo "Version OK: $trim"
+        else
+          echo "Invalid version: $trim"
+          exit 1
+        fi
+        echo "VERSION=${trim}" >> $GITHUB_ENV
 
-  #   - name: Checkout
-  #     uses: actions/checkout@v3
-  #     with:
-  #       submodules: true
-  #       ref: ${{ github.event.ref }}
+    - name: Checkout
+      uses: actions/checkout@v3
+      with:
+        submodules: true
+        ref: ${{ github.event.ref }}
 
-  #   - name: Set up Go
-  #     uses: actions/setup-go@v4
-  #     with:
-  #       go-version: 1.19
+    - name: Set up Go
+      uses: actions/setup-go@v4
+      with:
+        go-version: 1.19
 
-  #   - name: Setup BATS
-  #     uses: mig4/setup-bats@v1
-  #     with:
-  #       bats-version: 1.2.1
+    - name: Setup BATS
+      uses: mig4/setup-bats@v1
+      with:
+        bats-version: 1.2.1
 
-  #   - name: Prepare for downloads
-  #     id: prepare-for-downloads
-  #     run: |
-  #       mkdir ~/artifacts
+    - name: Prepare for downloads
+      id: prepare-for-downloads
+      run: |
+        mkdir ~/artifacts
 
-  #   - name: Download Darwin Build Artifacts
-  #     uses: actions/download-artifact@v3
-  #     if: ${{ matrix.platform == 'macos-latest' }}
-  #     with:
-  #       name: build-artifact-darwin
-  #       path: ~/artifacts
+    - name: Download Darwin Build Artifacts
+      uses: actions/download-artifact@v3
+      if: ${{ matrix.platform == 'macos-latest' }}
+      with:
+        name: build-artifact-darwin
+        path: ~/artifacts
 
-  #   - name: Extract Darwin Artifacts and Install Binary
-  #     if: ${{ matrix.platform == 'macos-latest' }}
-  #     run: |
-  #       mkdir ~/build
-  #       unzip ~/artifacts/darwin.zip -d ~/build
+    - name: Extract Darwin Artifacts and Install Binary
+      if: ${{ matrix.platform == 'macos-latest' }}
+      run: |
+        mkdir ~/build
+        unzip ~/artifacts/darwin.zip -d ~/build
 
-  #   - name: Set PATH
-  #     run: |
-  #       echo "PATH=$PATH:$HOME/build:$GTIHUB_WORKSPACE/tests/acceptance/lib/bats-core/libexec" >> $GITHUB_ENV
+    - name: Set PATH
+      run: |
+        echo "PATH=$PATH:$HOME/build:$GTIHUB_WORKSPACE/tests/acceptance/lib/bats-core/libexec" >> $GITHUB_ENV
 
-  #   - name: Go install jd
-  #     run: |
-  #       go install github.com/josephburnett/jd@latest
+    - name: Go install jd
+      run: |
+        go install github.com/josephburnett/jd@latest
 
-  #   - name: Install DB
-  #     id: install-db
-  #     continue-on-error: false
-  #     run: |
-  #       steampipe service start
-  #       steampipe plugin install chaos chaosdynamic
-  #       steampipe service stop
+    - name: Install DB
+      id: install-db
+      continue-on-error: false
+      run: |
+        steampipe service start
+        steampipe plugin install chaos chaosdynamic
+        steampipe service stop
 
-  #   - name: Run Test Suite
-  #     id: run-test-suite
-  #     timeout-minutes: 15
-  #     run: |
-  #       chmod +x $GITHUB_WORKSPACE/tests/acceptance/run.sh
-  #       $GITHUB_WORKSPACE/tests/acceptance/run.sh ${{ matrix.test_block }}.bats
-  #       steampipe service stop --force
+    - name: Run Test Suite
+      id: run-test-suite
+      timeout-minutes: 15
+      run: |
+        chmod +x $GITHUB_WORKSPACE/tests/acceptance/run.sh
+        $GITHUB_WORKSPACE/tests/acceptance/run.sh ${{ matrix.test_block }}.bats
+        steampipe service stop --force
 
   linux_arm_acceptance_tests:
     name: Linux ARM64 acceptance tests
-    needs: [create_test_build]
+    needs: [create_test_build,build_and_release_assets]
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
@@ -515,7 +515,7 @@ jobs:
 
   create_release_tag:
     name: Tag Release
-    needs: [linux_arm_acceptance_tests]
+    needs: [run_acceptance_tests,linux_arm_acceptance_tests]
     runs-on: ubuntu-latest
     steps:
     - name: Trim asset version prefix and Validate
