add to workflow

diff --git a/.github/workflows/release_cli_and_assets.yml b/.github/workflows/release_cli_and_assets.yml
--- a/.github/workflows/release_cli_and_assets.yml
+++ b/.github/workflows/release_cli_and_assets.yml
@@ -18,6 +18,7 @@ env:
   CONFIG_SCHEMA_VERSION: "2020-11-18"
   VERSION: ${{ github.event.inputs.version }}
   STEAMPIPE_UPDATE_CHECK: false
+  GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
 
 jobs:
 
@@ -229,151 +230,151 @@ jobs:
         image-to-tag: "${{ steps.image_ref.outputs.REF }}"
         image-version: ${{ env.VERSION }}
 
-  create_test_build:
-    name: Create Test Build
-    runs-on: ubuntu-latest
-    needs: [verify_input]
-    steps:
-    - name: Trim asset version prefix and Validate
-      run: |-
-        echo $VERSION
-        trim=${VERSION#"v"}
-        echo $trim
-        if [[ $trim =~  ^[0-9]+\.[0-9]+\.[0-9]+(-.+)?$ ]]; then
-          echo "Version OK: $trim"
-        else
-          echo "Invalid version: $trim"
-          exit 1
-        fi
-        echo "VERSION=${trim}" >> $GITHUB_ENV
+  # create_test_build:
+  #   name: Create Test Build
+  #   runs-on: ubuntu-latest
+  #   needs: [verify_input]
+  #   steps:
+  #   - name: Trim asset version prefix and Validate
+  #     run: |-
+  #       echo $VERSION
+  #       trim=${VERSION#"v"}
+  #       echo $trim
+  #       if [[ $trim =~  ^[0-9]+\.[0-9]+\.[0-9]+(-.+)?$ ]]; then
+  #         echo "Version OK: $trim"
+  #       else
+  #         echo "Invalid version: $trim"
+  #         exit 1
+  #       fi
+  #       echo "VERSION=${trim}" >> $GITHUB_ENV
         
-    - name: Checkout
-      uses: actions/checkout@v3
-      with:
-        ref: ${{ github.event.inputs.branch }}
+  #   - name: Checkout
+  #     uses: actions/checkout@v3
+  #     with:
+  #       ref: ${{ github.event.inputs.branch }}
 
-    - name: Unshallow
-      run: git fetch
+  #   - name: Unshallow
+  #     run: git fetch
 
-    - name: Set up Go
-      uses: actions/setup-go@v3
-      with:
-        go-version: 1.18
+  #   - name: Set up Go
+  #     uses: actions/setup-go@v3
+  #     with:
+  #       go-version: 1.18
 
-    - name: Run GoReleaser
-      uses: goreleaser/goreleaser-action@v3
-      with:
-        version: latest
-        args: release --snapshot --rm-dist --skip-publish
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #   - name: Run GoReleaser
+  #     uses: goreleaser/goreleaser-action@v3
+  #     with:
+  #       version: latest
+  #       args: release --snapshot --rm-dist --skip-publish
+  #     env:
+  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-    - name: Move build artifacts
-      run: |
-        mkdir ~/artifacts
-        mv $GITHUB_WORKSPACE/dist/steampipe_linux_amd64.tar.gz ~/artifacts/linux.tar.gz
-        mv $GITHUB_WORKSPACE/dist/steampipe_darwin_amd64.zip ~/artifacts/darwin.zip
+  #   - name: Move build artifacts
+  #     run: |
+  #       mkdir ~/artifacts
+  #       mv $GITHUB_WORKSPACE/dist/steampipe_linux_amd64.tar.gz ~/artifacts/linux.tar.gz
+  #       mv $GITHUB_WORKSPACE/dist/steampipe_darwin_amd64.zip ~/artifacts/darwin.zip
 
-    - name: List Build Artifacts
-      run: ls -l ~/artifacts
+  #   - name: List Build Artifacts
+  #     run: ls -l ~/artifacts
 
-    - name: Save Linux Build Artifact
-      uses: actions/upload-artifact@v3
-      with:
-        name: build-artifact-linux
-        path: ~/artifacts/linux.tar.gz
-        if-no-files-found: error
+  #   - name: Save Linux Build Artifact
+  #     uses: actions/upload-artifact@v3
+  #     with:
+  #       name: build-artifact-linux
+  #       path: ~/artifacts/linux.tar.gz
+  #       if-no-files-found: error
 
-    - name: Save MacOS Build Artifact
-      uses: actions/upload-artifact@v3
-      with:
-        name: build-artifact-darwin
-        path: ~/artifacts/darwin.zip
-        if-no-files-found: error
+  #   - name: Save MacOS Build Artifact
+  #     uses: actions/upload-artifact@v3
+  #     with:
+  #       name: build-artifact-darwin
+  #       path: ~/artifacts/darwin.zip
+  #       if-no-files-found: error
 
-  run_acceptance_tests:
-    name: Run CLI Acceptance tests
-    needs: [create_test_build,build_and_release_assets]
-    strategy:
-      matrix:
-        platform: [ macos-latest ]
-    runs-on: ${{ matrix.platform }}
-    steps:
-    - name: Trim asset version prefix and Validate
-      run: |-
-        echo $VERSION
-        trim=${VERSION#"v"}
-        echo $trim
-        if [[ $trim =~  ^[0-9]+\.[0-9]+\.[0-9]+(-.+)?$ ]]; then
-          echo "Version OK: $trim"
-        else
-          echo "Invalid version: $trim"
-          exit 1
-        fi
-        echo "VERSION=${trim}" >> $GITHUB_ENV
+  # run_acceptance_tests:
+  #   name: Run CLI Acceptance tests
+  #   needs: [create_test_build,build_and_release_assets]
+  #   strategy:
+  #     matrix:
+  #       platform: [ macos-latest ]
+  #   runs-on: ${{ matrix.platform }}
+  #   steps:
+  #   - name: Trim asset version prefix and Validate
+  #     run: |-
+  #       echo $VERSION
+  #       trim=${VERSION#"v"}
+  #       echo $trim
+  #       if [[ $trim =~  ^[0-9]+\.[0-9]+\.[0-9]+(-.+)?$ ]]; then
+  #         echo "Version OK: $trim"
+  #       else
+  #         echo "Invalid version: $trim"
+  #         exit 1
+  #       fi
+  #       echo "VERSION=${trim}" >> $GITHUB_ENV
 
-    - name: Checkout
-      uses: actions/checkout@v3
-      with:
-        submodules: true
-        ref: ${{ github.event.inputs.branch }}
+  #   - name: Checkout
+  #     uses: actions/checkout@v3
+  #     with:
+  #       submodules: true
+  #       ref: ${{ github.event.inputs.branch }}
 
-    - name: Setup BATS
-      uses: mig4/setup-bats@v1
-      with:
-        bats-version: 1.2.1
+  #   - name: Setup BATS
+  #     uses: mig4/setup-bats@v1
+  #     with:
+  #       bats-version: 1.2.1
 
-    - name: Prepare for downloads
-      id: prepare-for-downloads
-      run: |
-        mkdir ~/artifacts
+  #   - name: Prepare for downloads
+  #     id: prepare-for-downloads
+  #     run: |
+  #       mkdir ~/artifacts
 
-    - name: Download Linux Build Artifacts
-      uses: actions/download-artifact@v3
-      if: ${{ matrix.platform == 'ubuntu-latest' }}
-      with:
-        name: build-artifact-linux
-        path: ~/artifacts
+  #   - name: Download Linux Build Artifacts
+  #     uses: actions/download-artifact@v3
+  #     if: ${{ matrix.platform == 'ubuntu-latest' }}
+  #     with:
+  #       name: build-artifact-linux
+  #       path: ~/artifacts
 
-    - name: Download Darwin Build Artifacts
-      uses: actions/download-artifact@v3
-      if: ${{ matrix.platform == 'macos-latest' }}
-      with:
-        name: build-artifact-darwin
-        path: ~/artifacts
+  #   - name: Download Darwin Build Artifacts
+  #     uses: actions/download-artifact@v3
+  #     if: ${{ matrix.platform == 'macos-latest' }}
+  #     with:
+  #       name: build-artifact-darwin
+  #       path: ~/artifacts
 
-    - name: Extract Darwin Artifacts and Install Binary
-      if: ${{ matrix.platform == 'macos-latest' }}
-      run: |
-        mkdir ~/build
-        unzip ~/artifacts/darwin.zip -d ~/build
+  #   - name: Extract Darwin Artifacts and Install Binary
+  #     if: ${{ matrix.platform == 'macos-latest' }}
+  #     run: |
+  #       mkdir ~/build
+  #       unzip ~/artifacts/darwin.zip -d ~/build
 
-    - name: Extract Ubuntu Artifacts and Install Binary
-      if: ${{ matrix.platform == 'ubuntu-latest' }}
-      run: |
-        mkdir ~/build
-        tar -xf ~/artifacts/linux.tar.gz -C ~/build
+  #   - name: Extract Ubuntu Artifacts and Install Binary
+  #     if: ${{ matrix.platform == 'ubuntu-latest' }}
+  #     run: |
+  #       mkdir ~/build
+  #       tar -xf ~/artifacts/linux.tar.gz -C ~/build
 
-    - name: Set PATH
-      run: |
-        echo "PATH=$PATH:$HOME/build:$GTIHUB_WORKSPACE/tests/acceptance/lib/bats/bin" >> $GITHUB_ENV
+  #   - name: Set PATH
+  #     run: |
+  #       echo "PATH=$PATH:$HOME/build:$GTIHUB_WORKSPACE/tests/acceptance/lib/bats/bin" >> $GITHUB_ENV
 
-    - name: Install DB
-      run: |
-        steampipe service start
-        steampipe plugin install chaos
-        steampipe service stop --force
+  #   - name: Install DB
+  #     run: |
+  #       steampipe service start
+  #       steampipe plugin install chaos
+  #       steampipe service stop --force
 
-    - name: Run Test Suite
-      timeout-minutes: 30
-      run: |
-        chmod +x $GITHUB_WORKSPACE/tests/acceptance/run.sh
-        $GITHUB_WORKSPACE/tests/acceptance/run.sh
-        steampipe service stop --force
+  #   - name: Run Test Suite
+  #     timeout-minutes: 30
+  #     run: |
+  #       chmod +x $GITHUB_WORKSPACE/tests/acceptance/run.sh
+  #       $GITHUB_WORKSPACE/tests/acceptance/run.sh
+  #       steampipe service stop --force
   
   create_release_tag:
     name: Tag Release
-    needs: [run_acceptance_tests]
+    needs: [build_and_release_assets]
     runs-on: ubuntu-latest
     steps:
     - name: Trim asset version prefix and Validate
@@ -404,9 +405,42 @@ jobs:
         git tag ${{ github.event.inputs.version }}
         git push origin ${{ github.event.inputs.version }}
 
+  ensure_branch_in_homebrew:
+    name: Ensure branch exists in homebrew-tap
+    needs: [create_release_tag]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Parse semver string
+        id: semver_parser
+        uses: booxmedialtd/ws-action-parse-semver@v1
+        with:
+          input_string: ${{ github.event.inputs.version }}
+
+      - name: Checkout
+        if: steps.semver_parser.outputs.prerelease == ''
+        uses: actions/checkout@v3
+        with:
+          repository: turbot/homebrew-tap
+          token: ${{ secrets.GH_ACCESS_TOKEN }}
+          ref: main
+
+      - name: Delete base branch if exists
+        if: steps.semver_parser.outputs.prerelease == ''
+        run: |
+          git fetch --all
+          git push origin --delete bump-brew
+          git push origin --delete $VERSION
+        continue-on-error: true
+
+      - name: Create base branch
+        if: steps.semver_parser.outputs.prerelease == ''
+        run: |
+          git checkout -b bump-brew
+          git push --set-upstream origin bump-brew
+
   build_and_release_cli:
     name: Release CLI
-    needs: [create_release_tag]
+    needs: [create_release_tag, ensure_branch_in_homebrew]
     runs-on: ubuntu-latest
     steps:
     - name: Trim asset version prefix and Validate
@@ -441,7 +475,7 @@ jobs:
         version: latest
         args: release --rm-dist
       env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
 
     # - name: Setup GCloud
     #   uses: google-github-actions/setup-gcloud@v0.6.0
@@ -460,6 +494,46 @@ jobs:
     #     gcloud beta artifacts yum upload steampipe-yum-repo --location=us --source=$GITHUB_WORKSPACE/dist/steampipe_linux_amd64.rpm --project steampipe
     #     gcloud beta artifacts apt upload steampipe-apt-repo --location=us --source=$GITHUB_WORKSPACE/dist/steampipe_linux_amd64.deb --project steampipe
 
+  create_pr_in_homebrew:
+    name: Create PR in homebrew-tap
+    needs: [ensure_branch_in_homebrew, build_and_release_cli]
+    runs-on: ubuntu-latest
+    env:
+      Version: ${{ github.event.inputs.version }}
+    steps:
+      - name: Parse semver string
+        id: semver_parser
+        uses: booxmedialtd/ws-action-parse-semver@v1
+        with:
+          input_string: ${{ github.event.inputs.version }}
+
+      - name: Checkout
+        if: steps.semver_parser.outputs.prerelease == ''
+        uses: actions/checkout@v3
+        with:
+          repository: turbot/homebrew-tap
+          token: ${{ secrets.GH_ACCESS_TOKEN }}
+          ref: main
+
+      - name: Create a new branch off the base branch
+        if: steps.semver_parser.outputs.prerelease == ''
+        run: |
+          git fetch --all
+          git checkout bump-brew
+          git checkout -b $VERSION
+          git push --set-upstream origin $VERSION
+
+      - name: Close pull request if already exists
+        if: steps.semver_parser.outputs.prerelease == ''
+        run: |
+          gh pr close $VERSION
+        continue-on-error: true
+
+      - name: Create pull request
+        if: steps.semver_parser.outputs.prerelease == ''
+        run: |
+          gh pr create --base main --head $VERSION --title "$Version" --body "Update formula"
+
   clean_up:
     # let's clean up the artifacts.
     # in case this step isn't reached,
@@ -467,7 +541,7 @@ jobs:
     # refer:
     #   https://docs.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts#downloading-and-deleting-artifacts-after-a-workflow-run-is-complete
     name: Clean Up Artifacts
-    needs: build_and_release_cli
+    needs: create_pr_in_homebrew
     runs-on: ubuntu-latest
     steps:
     - name: Clean up Linux Build
