update

diff --git a/.github/workflows/release_cli_and_assets.yml b/.github/workflows/release_cli_and_assets.yml
--- a/.github/workflows/release_cli_and_assets.yml
+++ b/.github/workflows/release_cli_and_assets.yml
@@ -230,151 +230,151 @@ jobs:
         image-to-tag: "${{ steps.image_ref.outputs.REF }}"
         image-version: ${{ env.VERSION }}
 
-  # create_test_build:
-  #   name: Create Test Build
-  #   runs-on: ubuntu-latest
-  #   needs: [verify_input]
-  #   steps:
-  #   - name: Trim asset version prefix and Validate
-  #     run: |-
-  #       echo $VERSION
-  #       trim=${VERSION#"v"}
-  #       echo $trim
-  #       if [[ $trim =~  ^[0-9]+\.[0-9]+\.[0-9]+(-.+)?$ ]]; then
-  #         echo "Version OK: $trim"
-  #       else
-  #         echo "Invalid version: $trim"
-  #         exit 1
-  #       fi
-  #       echo "VERSION=${trim}" >> $GITHUB_ENV
+  create_test_build:
+    name: Create Test Build
+    runs-on: ubuntu-latest
+    needs: [verify_input]
+    steps:
+    - name: Trim asset version prefix and Validate
+      run: |-
+        echo $VERSION
+        trim=${VERSION#"v"}
+        echo $trim
+        if [[ $trim =~  ^[0-9]+\.[0-9]+\.[0-9]+(-.+)?$ ]]; then
+          echo "Version OK: $trim"
+        else
+          echo "Invalid version: $trim"
+          exit 1
+        fi
+        echo "VERSION=${trim}" >> $GITHUB_ENV
         
-  #   - name: Checkout
-  #     uses: actions/checkout@v3
-  #     with:
-  #       ref: ${{ github.event.inputs.branch }}
+    - name: Checkout
+      uses: actions/checkout@v3
+      with:
+        ref: ${{ github.event.inputs.branch }}
 
-  #   - name: Unshallow
-  #     run: git fetch
+    - name: Unshallow
+      run: git fetch
 
-  #   - name: Set up Go
-  #     uses: actions/setup-go@v3
-  #     with:
-  #       go-version: 1.18
+    - name: Set up Go
+      uses: actions/setup-go@v3
+      with:
+        go-version: 1.18
 
-  #   - name: Run GoReleaser
-  #     uses: goreleaser/goreleaser-action@v3
-  #     with:
-  #       version: latest
-  #       args: release --snapshot --rm-dist --skip-publish
-  #     env:
-  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    - name: Run GoReleaser
+      uses: goreleaser/goreleaser-action@v3
+      with:
+        version: latest
+        args: release --snapshot --rm-dist --skip-publish
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-  #   - name: Move build artifacts
-  #     run: |
-  #       mkdir ~/artifacts
-  #       mv $GITHUB_WORKSPACE/dist/steampipe_linux_amd64.tar.gz ~/artifacts/linux.tar.gz
-  #       mv $GITHUB_WORKSPACE/dist/steampipe_darwin_amd64.zip ~/artifacts/darwin.zip
+    - name: Move build artifacts
+      run: |
+        mkdir ~/artifacts
+        mv $GITHUB_WORKSPACE/dist/steampipe_linux_amd64.tar.gz ~/artifacts/linux.tar.gz
+        mv $GITHUB_WORKSPACE/dist/steampipe_darwin_amd64.zip ~/artifacts/darwin.zip
 
-  #   - name: List Build Artifacts
-  #     run: ls -l ~/artifacts
+    - name: List Build Artifacts
+      run: ls -l ~/artifacts
 
-  #   - name: Save Linux Build Artifact
-  #     uses: actions/upload-artifact@v3
-  #     with:
-  #       name: build-artifact-linux
-  #       path: ~/artifacts/linux.tar.gz
-  #       if-no-files-found: error
+    - name: Save Linux Build Artifact
+      uses: actions/upload-artifact@v3
+      with:
+        name: build-artifact-linux
+        path: ~/artifacts/linux.tar.gz
+        if-no-files-found: error
 
-  #   - name: Save MacOS Build Artifact
-  #     uses: actions/upload-artifact@v3
-  #     with:
-  #       name: build-artifact-darwin
-  #       path: ~/artifacts/darwin.zip
-  #       if-no-files-found: error
+    - name: Save MacOS Build Artifact
+      uses: actions/upload-artifact@v3
+      with:
+        name: build-artifact-darwin
+        path: ~/artifacts/darwin.zip
+        if-no-files-found: error
 
-  # run_acceptance_tests:
-  #   name: Run CLI Acceptance tests
-  #   needs: [create_test_build,build_and_release_assets]
-  #   strategy:
-  #     matrix:
-  #       platform: [ macos-latest ]
-  #   runs-on: ${{ matrix.platform }}
-  #   steps:
-  #   - name: Trim asset version prefix and Validate
-  #     run: |-
-  #       echo $VERSION
-  #       trim=${VERSION#"v"}
-  #       echo $trim
-  #       if [[ $trim =~  ^[0-9]+\.[0-9]+\.[0-9]+(-.+)?$ ]]; then
-  #         echo "Version OK: $trim"
-  #       else
-  #         echo "Invalid version: $trim"
-  #         exit 1
-  #       fi
-  #       echo "VERSION=${trim}" >> $GITHUB_ENV
+  run_acceptance_tests:
+    name: Run CLI Acceptance tests
+    needs: [create_test_build,build_and_release_assets]
+    strategy:
+      matrix:
+        platform: [ macos-latest ]
+    runs-on: ${{ matrix.platform }}
+    steps:
+    - name: Trim asset version prefix and Validate
+      run: |-
+        echo $VERSION
+        trim=${VERSION#"v"}
+        echo $trim
+        if [[ $trim =~  ^[0-9]+\.[0-9]+\.[0-9]+(-.+)?$ ]]; then
+          echo "Version OK: $trim"
+        else
+          echo "Invalid version: $trim"
+          exit 1
+        fi
+        echo "VERSION=${trim}" >> $GITHUB_ENV
 
-  #   - name: Checkout
-  #     uses: actions/checkout@v3
-  #     with:
-  #       submodules: true
-  #       ref: ${{ github.event.inputs.branch }}
+    - name: Checkout
+      uses: actions/checkout@v3
+      with:
+        submodules: true
+        ref: ${{ github.event.inputs.branch }}
 
-  #   - name: Setup BATS
-  #     uses: mig4/setup-bats@v1
-  #     with:
-  #       bats-version: 1.2.1
+    - name: Setup BATS
+      uses: mig4/setup-bats@v1
+      with:
+        bats-version: 1.2.1
 
-  #   - name: Prepare for downloads
-  #     id: prepare-for-downloads
-  #     run: |
-  #       mkdir ~/artifacts
+    - name: Prepare for downloads
+      id: prepare-for-downloads
+      run: |
+        mkdir ~/artifacts
 
-  #   - name: Download Linux Build Artifacts
-  #     uses: actions/download-artifact@v3
-  #     if: ${{ matrix.platform == 'ubuntu-latest' }}
-  #     with:
-  #       name: build-artifact-linux
-  #       path: ~/artifacts
+    - name: Download Linux Build Artifacts
+      uses: actions/download-artifact@v3
+      if: ${{ matrix.platform == 'ubuntu-latest' }}
+      with:
+        name: build-artifact-linux
+        path: ~/artifacts
 
-  #   - name: Download Darwin Build Artifacts
-  #     uses: actions/download-artifact@v3
-  #     if: ${{ matrix.platform == 'macos-latest' }}
-  #     with:
-  #       name: build-artifact-darwin
-  #       path: ~/artifacts
+    - name: Download Darwin Build Artifacts
+      uses: actions/download-artifact@v3
+      if: ${{ matrix.platform == 'macos-latest' }}
+      with:
+        name: build-artifact-darwin
+        path: ~/artifacts
 
-  #   - name: Extract Darwin Artifacts and Install Binary
-  #     if: ${{ matrix.platform == 'macos-latest' }}
-  #     run: |
-  #       mkdir ~/build
-  #       unzip ~/artifacts/darwin.zip -d ~/build
+    - name: Extract Darwin Artifacts and Install Binary
+      if: ${{ matrix.platform == 'macos-latest' }}
+      run: |
+        mkdir ~/build
+        unzip ~/artifacts/darwin.zip -d ~/build
 
-  #   - name: Extract Ubuntu Artifacts and Install Binary
-  #     if: ${{ matrix.platform == 'ubuntu-latest' }}
-  #     run: |
-  #       mkdir ~/build
-  #       tar -xf ~/artifacts/linux.tar.gz -C ~/build
+    - name: Extract Ubuntu Artifacts and Install Binary
+      if: ${{ matrix.platform == 'ubuntu-latest' }}
+      run: |
+        mkdir ~/build
+        tar -xf ~/artifacts/linux.tar.gz -C ~/build
 
-  #   - name: Set PATH
-  #     run: |
-  #       echo "PATH=$PATH:$HOME/build:$GTIHUB_WORKSPACE/tests/acceptance/lib/bats/bin" >> $GITHUB_ENV
+    - name: Set PATH
+      run: |
+        echo "PATH=$PATH:$HOME/build:$GTIHUB_WORKSPACE/tests/acceptance/lib/bats/bin" >> $GITHUB_ENV
 
-  #   - name: Install DB
-  #     run: |
-  #       steampipe service start
-  #       steampipe plugin install chaos
-  #       steampipe service stop --force
+    - name: Install DB
+      run: |
+        steampipe service start
+        steampipe plugin install chaos
+        steampipe service stop --force
 
-  #   - name: Run Test Suite
-  #     timeout-minutes: 30
-  #     run: |
-  #       chmod +x $GITHUB_WORKSPACE/tests/acceptance/run.sh
-  #       $GITHUB_WORKSPACE/tests/acceptance/run.sh
-  #       steampipe service stop --force
+    - name: Run Test Suite
+      timeout-minutes: 30
+      run: |
+        chmod +x $GITHUB_WORKSPACE/tests/acceptance/run.sh
+        $GITHUB_WORKSPACE/tests/acceptance/run.sh
+        steampipe service stop --force
   
   create_release_tag:
     name: Tag Release
-    needs: [build_and_release_assets]
+    needs: [run_acceptance_tests]
     runs-on: ubuntu-latest
     steps:
     - name: Trim asset version prefix and Validate
